### PR TITLE
Issue#123 Added favicon icon to the site

### PR DESCRIPTION
**Pull request by aabi01**
Issue#123
I have added the favicon icon to the php reboot website.

### CODE REVIEW

**Comment by aabi01** [comment]
Hi @kapilsharma ,
Please review the changes and let me know if anything needs to be changed.

**Comment by kapilsharma** [comment]
Thanks for changes @aabi01 
I've merged the PR.

**Comment by kapilsharma** [comment]
Tested on local. Seems good.
Creating PR to merge on master.

**Comment by kapilsharma** [comment]
https://github.com/phpreboot/website/pull/136 generated and merged.

**Comment by kapilsharma** [comment]
Live on master.
Close #123

**Comment by kapilsharma** [comment]
@aabi01 

We have a slack team of developers contributing on PHP Reboot. You can join slack channel at https://phpreboot.signup.team/

**Comment by kapilsharma** [comment]
@aabi01 

Are you on twitter? Please check this https://twitter.com/phpreboot/status/790031819592704000

**Comment by aabi01** [comment]
Thank you very much @kapilsharma  for merging my changes. 
I have registered for Slack channel. i am waiting their approval. I have also followed the Twitter handle.

**Pull request merged**
