### PR TITLE
Removes MagazineTableSeeder & August16ArticleSeeder #82

### PR DESCRIPTION
**Pull request by sahilsharma011**

### CODE REVIEW

**Comment by kapilsharma** [comment]
Merged.

PR #154 created for master branch. Merged to master as well.

**Comment by kapilsharma** [comment]
Thanks @sahilsharma011 

I added you as contributor. As contributor, you can directly commit on branched (except master and development) but please continue following PR way as other contributors.

Most important, as contributor, you can assign any issue to yourself and login to waffle.io/phpreboot/website using your github account and make comments there only. Now if you are working on any issue, just assign it to yourself so that there are no duplication of efforts.

**Comment by sahilsharma011** [comment]
Thank you @kapilsharma for adding me as a contributor. This are my first open source contributions, so I am excited about this.

**Comment by kapilsharma** [comment]
Welcome Sahil.

Open source is really awesome. I learned a lot through reading source code of several open source projects and contributed to few. I really believe `open source = open course`.

We have a PHP reboot slack channel, where all contributors have chat and few integration. You can get whole picture of issues/chats/ other integrations there. You can join slack at https://phpreboot.signup.team

We also have a what app chat group, for quick discussions. Share me your mobile number on slack PM and I'll add you to whatsapp group as well.

**Pull request merged**
